### ISSUE TITLE
Displaying variable in the browser

### ISSUE THREAD

**Issue by ddharshan** [ValerioB88/browser-dashboard#1]
Hi,
I am trying to display the episodes (variables) in the cartpole, on the browser, using Flask . Could you please tell me what is the html code for that ?

**Comment by ValerioB88** [comment]
Hi @ddharshan , it's not really that simple, it will require changing the HTML code, the `runcontro.js` , and some flask code too. I do not really have time for working on this right now, sorry!

**Comment by ValerioB88** [comment]
This is now fully supported using the TextInfo component.
